# These are supported funding model platforms

github: xhilmi # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: xhilmi # Replace with a single Patreon username
open_collective: xhilmi # Replace with a single Open Collective username
ko_fi: xhilmi # Replace with a single Ko-fi username
tidelift: xhilmi/cloudflare # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: xhilmi # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: xhilmi # Replace with a single Liberapay username
issuehunt: xhilmi # Replace with a single IssueHunt username
otechie: xhilmi # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
